apiVersion: v1
kind: Pod
metadata:
  name: homework1
  namespace: homework
spec:
  containers:
  - name: nginx
    image: nginx
    command: ["/bin/sh", "-c", "sed -i 's/listen  .*/listen 8000;/g' /etc/nginx/conf.d/default.conf && sed -i 's/usr\\/share\\/nginx\\/html/homework/g' /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: www
      mountPath: "/homework"
    lifecycle:
      preStop:
        exec:
          command: ["/usr/bin/rm", "-f", "/homework/index.html"]
  initContainers:
  - name: makeindex
    image: busybox:1.28
    command: ["sh", "-c", "echo \"<html>My first OTUS homework is done!</html>\" > /init/index.html"]
    volumeMounts:
    - name: www
      mountPath: "/init"
  volumes:
  - name: www
    emptyDir: {}

